inclusionAI/AWorld

README.md
aworld/agents/README.md
aworld/apps/android/run.py
aworld/apps/browsers/run.py
aworld/apps/gaia/run.py
aworld/apps/gym/run.py
aworld/core/client.py
aworld/core/envs/tool.py
aworld/core/envs/tool_desc.py
aworld/core/swarm.py
aworld/core/task.py
aworld/virtual_environments/README.md
aworld/virtual_environments/__init__.py
aworld/virtual_environments/android/action/executor.py
aworld/virtual_environments/android/android.py
aworld/virtual_environments/apis/search_api.py
aworld/virtual_environments/browsers/action/executor.py
aworld/virtual_environments/browsers/async_browser.py
aworld/virtual_environments/browsers/browser.py
aworld/virtual_environments/document/document.py
aworld/virtual_environments/gym/async_openai_gym.py
aworld/virtual_environments/gym/openai_gym.py
aworld/virtual_environments/interpreters/python_tool.py
aworld/virtual_environments/terminals/shell_tool.py

Client and task rewrite and refactor to make the structure in the framework clearer.

rewrite client and task

---

aworld/core/envs/tool.py
setup.py

add yaml in setup;

---

aworld/apps/README.md

add detailed description of apps

app readme optimization

---

aworld/requirements.txt

remove gradio

---

aworld/mcp/utils.py

mcp args array

---

aworld/config/mcp_tool.yaml
aworld/core/agent/base.py
aworld/core/task.py
aworld/utils/common.py
examples/search/run.py

asyncio run fix;
run sequence fix

asyncio run fix

---

aworld/utils/common.py

catch exception

---

aworld/mcp/server.py
aworld/virtual_environments/mcp/executor.py

Fix mcp asynchronous task cancellation issue

Fix mcp asynchronous task cancellation issue

---

aworld/mcp/decorator.py
aworld/utils/common.py
examples/mcp/run.py
examples/mcp/simple_server.py

The class is announced as MCP Server.

The class is announced as MCP Server.

---

aworld/core/agent/base.py
aworld/models/llm.py
aworld/models/llm_http_handler.py

Fix logic for initializing llm.

fix(agent):Fix logic for initializing llm

---

aworld/mcp/utils.py

fix mcp mcp_tool_desc_transform

fix mcp mcp_tool_desc_transform

---

aworld/events/__init__.py
aworld/events/async_event.py
aworld/events/async_init.py
aworld/events/async_pub_event.py
aworld/events/async_sub_event.py
examples/events/async_unittest.py

async event

---

aworld/models/README.md
aworld/models/llm.py
aworld/models/llm_http_handler.py
aworld/models/shangshu_provider.py
aworld/requirements.txt

- Implement ShangshuProvider class with support for various API call patterns
- Update LLM HTTP handler for Shangshu API integration
- Standardize documentation and error handling

Merge Shangshu LLM provider

---

aworld/models/llm.py

fix: Correct the Key of LLM config.

fix(models):get llm config

---

mcp_servers/browser_server.py
mcp_servers/document_server.py
mcp_servers/download_server.py
mcp_servers/reasoning_server.py
mcp_servers/search_server.py

mcp servers for gaia docker env

adding necessary docker mcp servers

---

aworld/core/agent/base.py
aworld/runners/sequence.py
aworld/runners/social.py
aworld/runners/task_runner.py
aworld/trace/opentelemetry/memory_storage.py
aworld/trace/rl_trace_processor.py

add span data to replay task execution

Gaia benchmark add replay

---

Dockerfile_gaia
aworld/runners/call_driven_runner.py

Fix bug: Docker env apt-get GPG key error

Fix bug: Docker env apt-get GPG key error

---

Dockerfile_gaia
aworld/__main__.py
aworld/core/agent/base.py
aworld/mcp_client/server.py
aworld/models/llm.py
aworld/requirements.txt
aworld/runner.py
aworld/trace/opentelemetry/memory_storage.py
aworld/trace/server/__init__.py
aworld/trace/server/routes.py
aworld/web/chat.py
aworld/web/cli.py
aworld/web/main.py
aworld/web/trace.py
aworld/web/trace_net.py
aworld/web/utils.py
examples/__init__.py
examples/gaia/gaia_agent_runner.py
examples/web/README.md
examples/web/__init__.py
examples/web/agent_deploy/gaia_agent/agent.py
examples/web/requirements.txt
run-server.sh

Gaia benchmark trace merge.main

Gaia benchmark trace merge.main

---

aworlddistributed/aworldspace/agents/gaia_agent.py
aworlddistributed/aworldspace/db/db.py
aworlddistributed/aworldspace/routes/tasks.py
aworlddistributed/base.py
aworlddistributed/client/aworld_client.py
aworlddistributed/requirements.txt

Framework upgrade aworldserver gaia main

---

aworld/core/llm_provider_base.py
aworld/models/llm.py
aworld/models/openai_provider.py

- add speech_to_text function in openai_provider

feat(model):add speech_to_text

---

aworld/config/conf.py
aworld/core/agent/base.py
aworld/core/agent/llm_agent.py
aworld/core/event/base.py
aworld/core/llm_provider_base.py
aworld/core/tool/base.py
aworld/models/llm.py
aworld/models/model_response.py
aworld/output/ui/base.py
aworld/runners/event_runner.py
aworld/runners/handler/agent.py
aworld/runners/handler/output.py
aworlddistributed/aworldspace/agents/playwright_agent.py

- add output event handler
- add llm_and_tool_execution to llm_agent

add_output_event

---

README.md

Guys it is 2025 today~ not 2024

fix news date

---

aworld/core/agent/base.py
aworld/core/agent/llm_agent.py
aworld/core/tool/base.py

fix eventbus

---

aworld/agents/llm_agent.py
aworld/runners/call_driven_runner.py

update agent/tool input to message

update agent/tool input to message

---

examples/android/agent.py

fix AndroidAgent.reset about Agent.reset

---

examples/gaia/README.md

new web ui

---

aworld/replay_buffer/event_replay_buffer.py

Event_replay_buffer:add export_to_oss

Event_replay_buffer:add export_to_oss

---

README.md
README_zh.md
examples/imo/README.md
examples/imo/guard_tool_caller.py
examples/imo/run.py

add imo example

---

README.md

Hi, I am a native English speaker (and former English teacher), and just wanted to help with the important and impactful phrasing you use as a quotation at the top of your Readme. I simply changed one word so that it sounds natural and gives a solid first impression.
Best of luck with your project!

Important fix to wording at the top of Readme

---

aworld/core/agent/base.py

Allow users to construct agents from environment variables conveniently.
`AgentConfig` is no longer required explicitly.
```python
import os
from aworld.agents.llm_agent import Agent
from aworld.runner import Runners
summarizer = Agent(
name="Summary Agent", 
system_prompt="You specialize at summarizing.",
)
result = Runners.sync_run(
input="Tell me a succint history about the universe", 
agent=summarizer,
)
```
As long as user specifies corresponding env vars.
```bash
export LLM_MODEL_NAME="gpt-4"
export LLM_API_KEY="your-api-key-here"
export LLM_BASE_URL="https://api.openai.com/v1"
```
The system raises a exception if neither env vars set or AgentConfig passed.
- User constructs agents in a lightweight fashion.
- Documents are more concise avoiding boilerplate code templates.

fea:construct agent from env vars by default

---

aworld/agents/llm_agent.py
aworld/config/conf.py
aworld/logs/opentelemetry/otlp_log.py
aworld/runners/event_runner.py
examples/browser_use/agent.py
examples/multi_agents/coordination/deepresearch/run.py
examples/phone_use/agent.py

based [PR341](https://github.com/inclusionAI/AWorld/pull/341)

unified llm conf in examples

---

examples/imo/guard_tool_caller.py
examples/imo/run.py

fix imo example

---

aworld/core/runtime_engine.py
aworld/memory/longterm/default.py
aworld/tools/function_tools.py
aworld/utils/common.py

This pull request introduces a series of targeted refactorings across the
AWorld codebase. The primary goal of these changes is to improve code
quality, reduce complexity, and enhance maintainability without altering
existing functionality.
Key Improvements:
* `core/runtime_engine.py`:
* Made the execution timeout in LocalRuntime configurable, replacing a
hardcoded value to improve flexibility.
* Re-added the K8sRuntime and KubernetesRuntime classes, which were
inadvertently removed in a previous refactoring. These classes serve as
placeholders for future Kubernetes integration.
* `memory/longterm/default.py`:
* Abstracted the LLM data extraction logic into a shared helper method
(_extract_data_from_llm).
* This refactoring eliminates significant code duplication between the …

Refactor: Core Component Improvements for Maintainability and Clarity

---

aworld/models/llm.py

feat(llm): compatible for model_config and agent_config
- Enhance compatibility between ModelConfig and AgentConfig
- Optimize configuration handling logic in LLMModel initialization

feat(llm): compatible for model_config and agent_config

---

aworld/core/event/base.py
aworld/events/manager.py
aworld/runners/handler/group.py
aworld/runners/state_manager.py
aworld/utils/run_util.py

- Make sure that event_manager get task_id from context.task.
- Set group_meta_data to group for context restoration.
- Pass outputs instance to agent task.

Dev aworldcore coding

---

aworld/mcp_client/server.py

fix mcp connection exception

---

aworld/agents/llm_agent.py
aworld/agents/parallel_llm_agent.py
aworld/agents/serial_llm_agent.py
aworld/core/agent/base.py
aworld/core/agent/swarm.py
aworld/runners/call_driven_runner.py
aworlddistributed/aworldspace/agents/playwright_agent.py
examples/multi_agents/coordination/custom_agent/agent.py

add `agent_result` as agent one interaction response;
add `task` as agent raw task;

llm agent in/out

---

aworld/agents/README-multi-agent.md
aworld/agents/llm_agent.py
aworld/agents/task_llm_agent.py
aworld/core/agent/swarm.py
aworld/utils/run_util.py

Fusion of different paradigms of multi-agent interaction, supporting swarm nesting for very complex interactions of multi-agent

[Agent] supported swarm nested

---

aworld/agents/llm_agent.py
aworld/memory/main.py
aworld/memory/models.py

[[CONTEXT] add message summary support](https://github.com/inclusionAI/AWorld/commit/54cb59d4c1bfc609b4a4289dfd6217f5d2c80d60)
[[CONTEXT] add fact support](https://github.com/inclusionAI/AWorld/commit/92d5ec9612b900bbafa31203f42c22fbd273a47f)

[CONTEXT] add message summary& step fact support]

---

examples/osworld/README.md
examples/osworld/run_multienv_aworldAgent.py

Osworld agent submit

---

aworld/agents/llm_agent.py
aworld/core/task.py
aworld/runners/event_runner.py
aworld/runners/handler/agent.py
aworld/runners/handler/base.py
aworld/runners/handler/group.py
aworld/runners/handler/output.py
aworld/runners/handler/task.py
aworld/runners/handler/tool.py

Cancel timeout task (default is long run task);
Cancel task and return input messages when the context length is too long.

feat(EventRunner): cancel task when timeout

---

aworld/logs/util.py
aworld/sandbox/base.py
aworld/sandbox/implementations/kubernetes_sandbox.py
aworld/sandbox/implementations/local_sandbox.py
aworld/sandbox/implementations/super_sandbox.py
aworld/trace/base.py
aworld/trace/config.py

- `__del__` use logging avoid deadlock problem
- AWorld logger adds `trace_id`

__del__ use logging
